import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryClientProvider from "@/utils/QueryClientProvider";
import { Toaster } from "@/components/primitives/toast/Toaster";
import Sidebar from "@/components/Sidebar";

const inter = localFont({
  src: [
    {
      path: "/../../public/InterVariable.ttf",
      style: "normal",
    },
    {
      path: "/../../public/InterVariable-Italic.ttf",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <body
          className={`${inter.className} flex h-screen flex-col-reverse bg-bg-0 text-text-950 sm:flex-row`}
        >
          <Toaster />
          <Sidebar />
          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
