import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/utils/QueryClientProvider";
import { Toaster } from "@/components/primitives/toast/Toaster";
import Resize from "@/utils/Resize";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <body className={inter.className + " flex min-h-screen text-text-900"}>
          <Toaster />
          <Resize>{children}</Resize>
        </body>
      </QueryClientProvider>
    </html>
  );
}
